name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Build binaries
        run: ./build.sh ${{ steps.version.outputs.VERSION }}

      - name: Create or update release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}               # Plain tag (v1.0.0)
          name: yj v${{ steps.version.outputs.VERSION }} # Human-friendly name
          draft: false
          prerelease: false
          overwrite: true
          fail_on_unmatched_files: true                  # Set to false temporarily if needed
          files: |
            build-v${{ steps.version.outputs.VERSION }}/yj-macos-amd64
            build-v${{ steps.version.outputs.VERSION }}/yj-macos-arm64
            build-v${{ steps.version.outputs.VERSION }}/yj-linux-amd64
            build-v${{ steps.version.outputs.VERSION }}/yj-linux-arm64
            build-v${{ steps.version.outputs.VERSION }}/yj-linux-arm-v5
            build-v${{ steps.version.outputs.VERSION }}/yj-linux-arm-v7
            build-v${{ steps.version.outputs.VERSION }}/yj.exe
            build-v${{ steps.version.outputs.VERSION }}/ty-macos-amd64
            build-v${{ steps.version.outputs.VERSION }}/ty-macos-arm64
            build-v${{ steps.version.outputs.VERSION }}/ty-linux-amd64
            build-v${{ steps.version.outputs.VERSION }}/ty-linux-arm64
            build-v${{ steps.version.outputs.VERSION }}/ty-linux-arm-v5
            build-v${{ steps.version.outputs.VERSION }}/ty-linux-arm-v7
            build-v${{ steps.version.outputs.VERSION }}/ty.exe
            build-v${{ steps.version.outputs.VERSION }}/yt-macos-amd64
            build-v${{ steps.version.outputs.VERSION }}/yt-macos-arm64
            build-v${{ steps.version.outputs.VERSION }}/yt-linux-amd64
            build-v${{ steps.version.outputs.VERSION }}/yt-linux-arm64
            build-v${{ steps.version.outputs.VERSION }}/yt-linux-arm-v5
            build-v${{ steps.version.outputs.VERSION }}/yt-linux-arm-v7
            build-v${{ steps.version.outputs.VERSION }}/yt.exe
